name: chess_clock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.0
  syncfusion_flutter_gauges: ^27.2.2
  wheel_picker: ^0.1.1
  flutter_native_splash: ^2.3.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icon/
  - assets/splash/

flutter_native_splash:
  color: "#FFFFFF" # Color de fondo
  image: assets/splash/splash_icon.png # Ruta al ícono de splash
  android_12:
    image: assets/splash/splash_icon.png
    color: "#ffffff"